package com.uptos.inventory.model;



import java.util.HashSet;
import java.util.Set;

/**
 * Almacen generated by hbm2java
 */
public class Almacen  implements java.io.Serializable {


     private int id;
     private Empresa empresa;
     private String nombre;
     private String direccion;
     private String telefono;
     private Set estantes = new HashSet(0);

    public Almacen() {
    }

	
    public Almacen(int id, Empresa empresa, String nombre, String direccion) {
        this.id = id;
        this.empresa = empresa;
        this.nombre = nombre;
        this.direccion = direccion;
    }
    public Almacen(int id, Empresa empresa, String nombre, String direccion, String telefono, Set estantes) {
       this.id = id;
       this.empresa = empresa;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.estantes = estantes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getEstantes() {
        return this.estantes;
    }
    
    public void setEstantes(Set estantes) {
        this.estantes = estantes;
    }




}


