package com.uptos.inventory.model;



import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private int id;
     private String categoria;
     private Set insumos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int id, String categoria) {
        this.id = id;
        this.categoria = categoria;
    }
    public Categoria(int id, String categoria, Set insumos) {
       this.id = id;
       this.categoria = categoria;
       this.insumos = insumos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Set getInsumos() {
        return this.insumos;
    }
    
    public void setInsumos(Set insumos) {
        this.insumos = insumos;
    }




}


