package com.uptos.inventory.model;



import java.util.Date;

/**
 * Comportamiento generated by hbm2java
 */
public class Comportamiento  implements java.io.Serializable {


     private int id;
     private Indicador indicador;
     private int valor;
     private String observacion;
     private Date fecha;

    public Comportamiento() {
    }

	
    public Comportamiento(int id, Indicador indicador, int valor, String observacion) {
        this.id = id;
        this.indicador = indicador;
        this.valor = valor;
        this.observacion = observacion;
    }
    public Comportamiento(int id, Indicador indicador, int valor, String observacion, Date fecha) {
       this.id = id;
       this.indicador = indicador;
       this.valor = valor;
       this.observacion = observacion;
       this.fecha = fecha;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Indicador getIndicador() {
        return this.indicador;
    }
    
    public void setIndicador(Indicador indicador) {
        this.indicador = indicador;
    }
    public int getValor() {
        return this.valor;
    }
    
    public void setValor(int valor) {
        this.valor = valor;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


