package com.uptos.inventory.model;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Compra generated by hbm2java
 */
public class Compra  implements java.io.Serializable {


     private int id;
     private Cuenta cuenta;
     private Proveedor proveedor;
     private Date fecha;
     private boolean estado;
     private String orden;
     private String factura;
     private Set detalleCompras = new HashSet(0);

    public Compra() {
    }

	
    public Compra(int id, Cuenta cuenta, Proveedor proveedor, Date fecha, boolean estado, String orden, String factura) {
        this.id = id;
        this.cuenta = cuenta;
        this.proveedor = proveedor;
        this.fecha = fecha;
        this.estado = estado;
        this.orden = orden;
        this.factura = factura;
    }
    public Compra(int id, Cuenta cuenta, Proveedor proveedor, Date fecha, boolean estado, String orden, String factura, Set detalleCompras) {
       this.id = id;
       this.cuenta = cuenta;
       this.proveedor = proveedor;
       this.fecha = fecha;
       this.estado = estado;
       this.orden = orden;
       this.factura = factura;
       this.detalleCompras = detalleCompras;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public boolean isEstado() {
        return this.estado;
    }
    
    public void setEstado(boolean estado) {
        this.estado = estado;
    }
    public String getOrden() {
        return this.orden;
    }
    
    public void setOrden(String orden) {
        this.orden = orden;
    }
    public String getFactura() {
        return this.factura;
    }
    
    public void setFactura(String factura) {
        this.factura = factura;
    }
    public Set getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set detalleCompras) {
        this.detalleCompras = detalleCompras;
    }




}


