package com.uptos.inventory.model;




/**
 * Cubiculo generated by hbm2java
 */
public class Cubiculo  implements java.io.Serializable {


     private int id;
     private Estante estante;
     private String nombre;

    public Cubiculo() {
    }

    public Cubiculo(int id, Estante estante, String nombre) {
       this.id = id;
       this.estante = estante;
       this.nombre = nombre;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estante getEstante() {
        return this.estante;
    }
    
    public void setEstante(Estante estante) {
        this.estante = estante;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


