package com.uptos.inventory.model;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private int id;
     private Persona persona;
     private String usuario;
     private String clave;
     private String rol;
     private String pregunta;
     private String respuesta;
     private Date ultimaConeccion;
     private Set pedidos = new HashSet(0);
     private Set compras = new HashSet(0);

    public Cuenta() {
    }

	
    public Cuenta(int id, Persona persona, String usuario, String clave, String rol, String pregunta, String respuesta) {
        this.id = id;
        this.persona = persona;
        this.usuario = usuario;
        this.clave = clave;
        this.rol = rol;
        this.pregunta = pregunta;
        this.respuesta = respuesta;
    }
    public Cuenta(int id, Persona persona, String usuario, String clave, String rol, String pregunta, String respuesta, Date ultimaConeccion, Set pedidos, Set compras) {
       this.id = id;
       this.persona = persona;
       this.usuario = usuario;
       this.clave = clave;
       this.rol = rol;
       this.pregunta = pregunta;
       this.respuesta = respuesta;
       this.ultimaConeccion = ultimaConeccion;
       this.pedidos = pedidos;
       this.compras = compras;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(String pregunta) {
        this.pregunta = pregunta;
    }
    public String getRespuesta() {
        return this.respuesta;
    }
    
    public void setRespuesta(String respuesta) {
        this.respuesta = respuesta;
    }
    public Date getUltimaConeccion() {
        return this.ultimaConeccion;
    }
    
    public void setUltimaConeccion(Date ultimaConeccion) {
        this.ultimaConeccion = ultimaConeccion;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


