package com.uptos.inventory.model;



import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * DetalleCompra generated by hbm2java
 */
public class DetalleCompra  implements java.io.Serializable {


     private int id;
     private Compra compra;
     private Insumo insumo;
     private int cantidad;
     private Boolean estado;
     private Integer registrados;
     private BigDecimal precio;
     private Integer devuelto;
     private Set unidads = new HashSet(0);

    public DetalleCompra() {
    }

	
    public DetalleCompra(int id, Compra compra, Insumo insumo, int cantidad, BigDecimal precio) {
        this.id = id;
        this.compra = compra;
        this.insumo = insumo;
        this.cantidad = cantidad;
        this.precio = precio;
    }
    public DetalleCompra(int id, Compra compra, Insumo insumo, int cantidad, Boolean estado, Integer registrados, BigDecimal precio, Integer devuelto, Set unidads) {
       this.id = id;
       this.compra = compra;
       this.insumo = insumo;
       this.cantidad = cantidad;
       this.estado = estado;
       this.registrados = registrados;
       this.precio = precio;
       this.devuelto = devuelto;
       this.unidads = unidads;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }
    public Insumo getInsumo() {
        return this.insumo;
    }
    
    public void setInsumo(Insumo insumo) {
        this.insumo = insumo;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Integer getRegistrados() {
        return this.registrados;
    }
    
    public void setRegistrados(Integer registrados) {
        this.registrados = registrados;
    }
    public BigDecimal getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(BigDecimal precio) {
        this.precio = precio;
    }
    public Integer getDevuelto() {
        return this.devuelto;
    }
    
    public void setDevuelto(Integer devuelto) {
        this.devuelto = devuelto;
    }
    public Set getUnidads() {
        return this.unidads;
    }
    
    public void setUnidads(Set unidads) {
        this.unidads = unidads;
    }




}


