package com.uptos.inventory.model;



import java.util.HashSet;
import java.util.Set;

/**
 * Indicador generated by hbm2java
 */
public class Indicador  implements java.io.Serializable {


     private int id;
     private String nombre;
     private int eficiente;
     private int critico;
     private String eficiencia;
     private String criticidad;
     private String aceptable;
     private Integer frecuencia;
     private Set comportamientos = new HashSet(0);

    public Indicador() {
    }

	
    public Indicador(int id, String nombre, int eficiente, int critico, String eficiencia, String criticidad, String aceptable) {
        this.id = id;
        this.nombre = nombre;
        this.eficiente = eficiente;
        this.critico = critico;
        this.eficiencia = eficiencia;
        this.criticidad = criticidad;
        this.aceptable = aceptable;
    }
    public Indicador(int id, String nombre, int eficiente, int critico, String eficiencia, String criticidad, String aceptable, Integer frecuencia, Set comportamientos) {
       this.id = id;
       this.nombre = nombre;
       this.eficiente = eficiente;
       this.critico = critico;
       this.eficiencia = eficiencia;
       this.criticidad = criticidad;
       this.aceptable = aceptable;
       this.frecuencia = frecuencia;
       this.comportamientos = comportamientos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEficiente() {
        return this.eficiente;
    }
    
    public void setEficiente(int eficiente) {
        this.eficiente = eficiente;
    }
    public int getCritico() {
        return this.critico;
    }
    
    public void setCritico(int critico) {
        this.critico = critico;
    }
    public String getEficiencia() {
        return this.eficiencia;
    }
    
    public void setEficiencia(String eficiencia) {
        this.eficiencia = eficiencia;
    }
    public String getCriticidad() {
        return this.criticidad;
    }
    
    public void setCriticidad(String criticidad) {
        this.criticidad = criticidad;
    }
    public String getAceptable() {
        return this.aceptable;
    }
    
    public void setAceptable(String aceptable) {
        this.aceptable = aceptable;
    }
    public Integer getFrecuencia() {
        return this.frecuencia;
    }
    
    public void setFrecuencia(Integer frecuencia) {
        this.frecuencia = frecuencia;
    }
    public Set getComportamientos() {
        return this.comportamientos;
    }
    
    public void setComportamientos(Set comportamientos) {
        this.comportamientos = comportamientos;
    }




}


