package com.uptos.inventory.model;



import java.util.HashSet;
import java.util.Set;

/**
 * Insumo generated by hbm2java
 */
public class Insumo  implements java.io.Serializable {


     private int id;
     private Categoria categoria;
     private String nombre;
     private String marca;
     private int minimo;
     private int maximo;
     private boolean perecedero;
     private int cantidad;
     private String codigo;
     private Set pereces = new HashSet(0);
     private Set detalleCompras = new HashSet(0);

    public Insumo() {
    }

	
    public Insumo(int id, Categoria categoria, String nombre, String marca, int minimo, int maximo, boolean perecedero, int cantidad, String codigo) {
        this.id = id;
        this.categoria = categoria;
        this.nombre = nombre;
        this.marca = marca;
        this.minimo = minimo;
        this.maximo = maximo;
        this.perecedero = perecedero;
        this.cantidad = cantidad;
        this.codigo = codigo;
    }
    public Insumo(int id, Categoria categoria, String nombre, String marca, int minimo, int maximo, boolean perecedero, int cantidad, String codigo, Set pereces, Set detalleCompras) {
       this.id = id;
       this.categoria = categoria;
       this.nombre = nombre;
       this.marca = marca;
       this.minimo = minimo;
       this.maximo = maximo;
       this.perecedero = perecedero;
       this.cantidad = cantidad;
       this.codigo = codigo;
       this.pereces = pereces;
       this.detalleCompras = detalleCompras;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public int getMinimo() {
        return this.minimo;
    }
    
    public void setMinimo(int minimo) {
        this.minimo = minimo;
    }
    public int getMaximo() {
        return this.maximo;
    }
    
    public void setMaximo(int maximo) {
        this.maximo = maximo;
    }
    public boolean isPerecedero() {
        return this.perecedero;
    }
    
    public void setPerecedero(boolean perecedero) {
        this.perecedero = perecedero;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set getPereces() {
        return this.pereces;
    }
    
    public void setPereces(Set pereces) {
        this.pereces = pereces;
    }
    public Set getDetalleCompras() {
        return this.detalleCompras;
    }
    
    public void setDetalleCompras(Set detalleCompras) {
        this.detalleCompras = detalleCompras;
    }




}


