package com.uptos.inventory.model;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private int id;
     private Cliente cliente;
     private Cuenta cuenta;
     private Date fecha;
     private Boolean estado;
     private Date recibido;
     private Set detallePedidos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(int id, Cliente cliente, Cuenta cuenta) {
        this.id = id;
        this.cliente = cliente;
        this.cuenta = cuenta;
    }
    public Pedido(int id, Cliente cliente, Cuenta cuenta, Date fecha, Boolean estado, Date recibido, Set detallePedidos) {
       this.id = id;
       this.cliente = cliente;
       this.cuenta = cuenta;
       this.fecha = fecha;
       this.estado = estado;
       this.recibido = recibido;
       this.detallePedidos = detallePedidos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getRecibido() {
        return this.recibido;
    }
    
    public void setRecibido(Date recibido) {
        this.recibido = recibido;
    }
    public Set getDetallePedidos() {
        return this.detallePedidos;
    }
    
    public void setDetallePedidos(Set detallePedidos) {
        this.detallePedidos = detallePedidos;
    }




}


