package com.uptos.inventory.model;



import java.util.Date;

/**
 * Perece generated by hbm2java
 */
public class Perece  implements java.io.Serializable {


     private int id;
     private Insumo insumo;
     private Date fecha;

    public Perece() {
    }

    public Perece(int id, Insumo insumo, Date fecha) {
       this.id = id;
       this.insumo = insumo;
       this.fecha = fecha;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Insumo getInsumo() {
        return this.insumo;
    }
    
    public void setInsumo(Insumo insumo) {
        this.insumo = insumo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


