package com.uptos.inventory.model;



import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String apellido;
     private String cedula;
     private String sexo;
     private String cargo;
     private String telefono;
     private Set cuentas = new HashSet(0);

    public Persona() {
    }

	
    public Persona(int id, String nombre, String apellido, String cedula, String sexo, String cargo) {
        this.id = id;
        this.nombre = nombre;
        this.apellido = apellido;
        this.cedula = cedula;
        this.sexo = sexo;
        this.cargo = cargo;
    }
    public Persona(int id, String nombre, String apellido, String cedula, String sexo, String cargo, String telefono, Set cuentas) {
       this.id = id;
       this.nombre = nombre;
       this.apellido = apellido;
       this.cedula = cedula;
       this.sexo = sexo;
       this.cargo = cargo;
       this.telefono = telefono;
       this.cuentas = cuentas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set cuentas) {
        this.cuentas = cuentas;
    }




}


