package com.uptos.inventory.model;



import java.util.HashSet;
import java.util.Set;

/**
 * Unidad generated by hbm2java
 */
public class Unidad  implements java.io.Serializable {


     private int id;
     private DetalleCompra detalleCompra;
     private int cubiculo;
     private Boolean estado;
     private String codigo;
     private Set detallePedidos = new HashSet(0);

    public Unidad() {
    }

	
    public Unidad(int id, DetalleCompra detalleCompra, int cubiculo) {
        this.id = id;
        this.detalleCompra = detalleCompra;
        this.cubiculo = cubiculo;
    }
    public Unidad(int id, DetalleCompra detalleCompra, int cubiculo, Boolean estado, String codigo, Set detallePedidos) {
       this.id = id;
       this.detalleCompra = detalleCompra;
       this.cubiculo = cubiculo;
       this.estado = estado;
       this.codigo = codigo;
       this.detallePedidos = detallePedidos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public DetalleCompra getDetalleCompra() {
        return this.detalleCompra;
    }
    
    public void setDetalleCompra(DetalleCompra detalleCompra) {
        this.detalleCompra = detalleCompra;
    }
    public int getCubiculo() {
        return this.cubiculo;
    }
    
    public void setCubiculo(int cubiculo) {
        this.cubiculo = cubiculo;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set getDetallePedidos() {
        return this.detallePedidos;
    }
    
    public void setDetallePedidos(Set detallePedidos) {
        this.detallePedidos = detallePedidos;
    }




}


